### ISSUE TITLE
src/index.js does not exist

### ISSUE THREAD

**Issue by jonasbz** [rowanwins/smallest-enclosing-circle#3]
package.json refers to `"main": "src/index.js"` which doesn't exist. So importing this package through `import smallestCircle from 'smallest-enclosing-circle';` throws an error.

I assume the solution is as simple as `"main": "src/main.js"`, but I have not been able to verify.

The workaround for now seems to be to include the compiled file directly: `import smallestCircle from 'smallest-enclosing-circle/dist/smallestEnclosingCircle'; `

**Comment by rowanwins** [comment]
Sorry for the slow reply @jonasbz - I'd somehow unwatched the repo!

I'll put out a new release.

**Comment by rowanwins** [comment]
Just published 1.0.1
